services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:8003
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - quiz-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=development
      - PORT=8003
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge
